services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=creditSystem'
      - 'POSTGRES_PASSWORD=admin123'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
